# Training configuration for cph
command:
  - python
  - ${program}
  - ${args}
# (required) Training script to run
program: train.py
# (required) specify the search strategy (grid, random, or bayes)
method: random
# Name of the sweep, displayed in UI
name: test-cph-sweep
# Text description of sweep
description: "First tests to get this working on CPH model"
# Specify metric to optimize (used by certain search strategies and stopping criteria)
metric:
  goal: minimize
  name: "Integrated brier score"
# (required) Parameter bounds to search. Model-dependent
parameters:
  l2:
    min: 0.0001
    max: 0.001

